// Generates src/environments/environment.ts at build time from env vars.
// Used by the production build on Render (set API_URL there).
// For local dev (`ng serve`), Angular swaps in environment.development.ts
// via the fileReplacements config in angular.json — this script is not needed locally.

const fs = require('fs');
const path = require('path');

// This script only runs during `npm run build` (production builds).
// Local `ng serve` uses environment.development.ts via Angular's fileReplacements,
// so we always set production=true here. Don't read NODE_ENV — setting it to
// "production" on Render makes npm skip devDependencies and breaks `ng`.
// Normalize: ensure exactly one trailing slash, so LlmService can safely concat
// `${apiUrl}api/v1/...` regardless of how API_URL was set in the dashboard.
const raw = process.env.API_URL ?? 'http://localhost:8080/';
const apiUrl = raw.replace(/\/+$/, '') + '/';
const sentryDsn = process.env.SENTRY_DSN ?? '';
const sentryEnvironment = process.env.SENTRY_ENVIRONMENT ?? 'production';
const production = true;

const target = path.join(__dirname, 'src', 'environments', 'environment.ts');
const content = `// AUTO-GENERATED by set-env.js — do not edit by hand, do not commit.
export const environment = {
  production: ${production},
  apiUrl: '${apiUrl}',
  sentryDsn: '${sentryDsn}',
  sentryEnvironment: '${sentryEnvironment}'
};
`;

fs.writeFileSync(target, content);
console.log(`[set-env] wrote ${target}`);
console.log(`[set-env]   production=${production}`);
console.log(`[set-env]   apiUrl=${apiUrl}`);
console.log(`[set-env]   sentryDsn=${sentryDsn ? 'configured' : 'not configured'}`);
console.log(`[set-env]   sentryEnvironment=${sentryEnvironment}`);
