// Generates src/environments/environment.ts at build time from env vars.
// Used by the production build on Render (set API_URL there).
// For local dev (`ng serve`), Angular swaps in environment.development.ts
// via the fileReplacements config in angular.json — this script is not needed locally.

const fs = require('fs');
const path = require('path');

const apiUrl = process.env.API_URL ?? 'http://localhost:8080/';
const production = process.env.NODE_ENV === 'production';

const target = path.join(__dirname, 'src', 'environments', 'environment.ts');
const content = `// AUTO-GENERATED by set-env.js — do not edit by hand, do not commit.
export const environment = {
  production: ${production},
  apiUrl: '${apiUrl}'
};
`;

fs.writeFileSync(target, content);
console.log(`[set-env] wrote ${target}`);
console.log(`[set-env]   production=${production}`);
console.log(`[set-env]   apiUrl=${apiUrl}`);
